package com.example.demo.entity.enums;

import lombok.Getter;

@Getter

public enum LaptopModel {
    // Apple
    MACBOOK_AIR_M1,
    MACBOOK_AIR_M2,
    MACBOOK_AIR_M3,
    MACBOOK_PRO_M1_PRO,
    MACBOOK_PRO_M2_PRO,
    MACBOOK_PRO_M3_PRO,
    MACBOOK_PRO_M3_MAX,

    // Asus
    ASUS_ROG_ZEPHYRUS_G14,
    ASUS_ROG_ZEPHYRUS_G16,
    ASUS_ROG_STRIX_G16,
    ASUS_ROG_STRIX_SCAR_18,
    ASUS_TUF_GAMING_A15,
    ASUS_TUF_GAMING_F15,
    ASUS_ZENBOOK_14_OLED,
    ASUS_VIVOBOOK_15,

    // Lenovo
    LENOVO_LEGION_5,
    LENOVO_LEGION_PRO_5,
    LENOVO_LEGION_PRO_7,
    LENOVO_LOQ_15,
    LENOVO_THINKPAD_X1_CARBON,
    LENOVO_THINKPAD_T14,
    LENOVO_IDEAPAD_3,
    LENOVO_IDEAPAD_GAMING_3,

    // Dell
    DELL_XPS_13,
    DELL_XPS_15,
    DELL_XPS_16,
    DELL_G15,
    DELL_G16,
    DELL_ALIENWARE_M16,
    DELL_ALIENWARE_M18,
    DELL_INSPIRON_15,

    // HP
    HP_VICTUS_15,
    HP_VICTUS_16,
    HP_OMEN_16,
    HP_OMEN_17,
    HP_PAVILION_15,
    HP_ENVY_X360,
    HP_SPECTRE_X360,

    // Acer
    ACER_NITRO_5,
    ACER_NITRO_16,
    ACER_PREDATOR_HELIOS_16,
    ACER_PREDATOR_HELIOS_18,
    ACER_SWIFT_3,
    ACER_SWIFT_GO_14,
    ACER_ASPIRE_5,

    // MSI
    MSI_KATANA_15,
    MSI_KATANA_17,
    MSI_THIN_GF63,
    MSI_CYBORG_15,
    MSI_PULSE_15,
    MSI_STEALTH_16_STUDIO,
    MSI_RAIDER_GE78,

    // Monster
    MONSTER_ABRA_A5,
    MONSTER_ABRA_A7,
    MONSTER_TULPAR_T5,
    MONSTER_TULPAR_T7,
    MONSTER_SEMURUK_S7
}
